Add feature: support Kotlin standard libraries.
When we add kotlin-stdlib-*.jar and kotlin-runtime-*.jar to a project, build error is occured.

ERROR: DEXmlvmOutputProcess-ref: Processing method: forEachLine
ERROR: DEXmlvmOutputProcess-ref: Failed while processing: The XML construct org.xmlvm.refcount.InstructionProcessor.process_nop(org.jdom.Element, org.xmlvm.refcount.InstructionUseInfo) could not be converted to a When attempting to: process_nop in TextStreamsKt
ERROR: DEXmlvmOutputProcess-ref: Processing method: relativeToOrSelf
ERROR: DEXmlvmOutputProcess-ref: Failed while processing: The XML construct org.xmlvm.refcount.InstructionProcessor.process_nop(org.jdom.Element, org.xmlvm.refcount.InstructionUseInfo) could not be converted to a When attempting to: process_nop in FilesKt__UtilsKt
ERROR: DEXmlvmOutputProcess-ref: Processing method: reader
ERROR: DEXmlvmOutputProcess-ref: Failed while processing: The XML construct org.xmlvm.refcount.InstructionProcessor.process_nop(org.jdom.Element, org.xmlvm.refcount.InstructionUseInfo) could not be converted to a When attempting to: process_nop in FilesKt__FileReadWriteKt
ERROR: DEXmlvmOutputProcess-ref: Processing method: find
ERROR: DEXmlvmOutputProcess-ref: Failed while processing: The XML construct org.xmlvm.refcount.InstructionProcessor.process_nop(org.jdom.Element, org.xmlvm.refcount.InstructionUseInfo) could not be converted to a When attempting to: process_nop in StringsKt___StringsKt
ERROR: DEXmlvmOutputProcess-ref: Processing method: replaceIndentByMargin
ERROR: DEXmlvmOutputProcess-ref: Failed while processing: The XML construct org.xmlvm.refcount.InstructionProcessor.process_nop(org.jdom.Element, org.xmlvm.refcount.InstructionUseInfo) could not be converted to a When attempting to: process_nop in StringsKt__IndentKt
ERROR: DEXmlvmOutputProcess-ref: Processing method: filterInPlace$CollectionsKt__MutableCollectionsKt
ERROR: DEXmlvmOutputProcess-ref: Failed while processing: The XML construct org.xmlvm.refcount.InstructionProcessor.process_nop(org.jdom.Element, org.xmlvm.refcount.InstructionUseInfo) could not be converted to a When attempting to: process_nop in CollectionsKt__MutableCollectionsKt
ERROR: DEXmlvmOutputProcess-ref: Processing method: mutableMapOf
ERROR: DEXmlvmOutputProcess-ref: Failed while processing: The XML construct org.xmlvm.refcount.InstructionProcessor.process_nop(org.jdom.Element, org.xmlvm.refcount.InstructionUseInfo) could not be converted to a When attempting to: process_nop in MapsKt__MapsKt
ERROR: DEXmlvmOutputProcess-ref: Processing method: getOrPut
ERROR: DEXmlvmOutputProcess-ref: Failed while processing: The XML construct org.xmlvm.refcount.InstructionProcessor.process_nop(org.jdom.Element, org.xmlvm.refcount.InstructionUseInfo) could not be converted to a When attempting to: process_nop in MapsKt__MapsJVMKt
ERROR: DEXmlvmOutputProcess-ref: Processing method: elementAtOrElse
ERROR: DEXmlvmOutputProcess-ref: Failed while processing: The XML construct org.xmlvm.refcount.InstructionProcessor.process_nop(org.jdom.Element, org.xmlvm.refcount.InstructionUseInfo) could not be converted to a When attempting to: process_nop in CollectionsKt___CollectionsKt
ERROR: DEXmlvmOutputProcess-ref: Processing method: find
ERROR: DEXmlvmOutputProcess-ref: Failed while processing: The XML construct org.xmlvm.refcount.InstructionProcessor.process_nop(org.jdom.Element, org.xmlvm.refcount.InstructionUseInfo) could not be converted to a When attempting to: process_nop in ArraysKt___ArraysKt
ERROR: DEXmlvmOutputProcess-ref: Processing method: getValue
ERROR: DEXmlvmOutputProcess-ref: Failed while processing: The XML construct org.xmlvm.refcount.InstructionProcessor.process_nop(org.jdom.Element, org.xmlvm.refcount.InstructionUseInfo) could not be converted to a When attempting to: process_nop in SynchronizedLazyImpl
ERROR: DEXmlvmOutputProcess-ref: Processing method: getOrSet
ERROR: DEXmlvmOutputProcess-ref: Failed while processing: The XML construct org.xmlvm.refcount.InstructionProcessor.process_nop(org.jdom.Element, org.xmlvm.refcount.InstructionUseInfo) could not be converted to a When attempting to: process_nop in ThreadsKt

dragome-bytecode-js-compiler doesn't support 'nop'.

This change support 'nop'.